# stockit-backend-chart/templates/db-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stockit-backend-chart.fullname" . }}-db-secret
  labels:
    {{- include "stockit-backend-chart.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64로 인코딩된 비밀번호를 여기에 직접 넣거나 (보안상 비추천),
  # kubectl create secret 명령으로 Secret을 먼저 생성해야 합니다.
  # 지금은 배포 편의를 위해 ConfigMap과 동일한 방식으로 참조할 이름을 설정합니다.
  POSTGRES_PASSWORD: {{ .Values.global.name | b64enc | quote }} # 임시 비밀번호 (예시)