# templates/db-service.yaml (예시)
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.host }} # Headless Service의 이름은 .Values.db.host와 일치해야 합니다.
  labels:
    {{- include "stockit-backend-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.db.name }}
spec:
  # Headless Service를 만들기 위해 clusterIP: None 설정이 중요합니다.
  clusterIP: None
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
      protocol: TCP
      name: postgres
    {{- if .Values.db.exporter.enabled }}
    - port: {{ .Values.db.exporter.port }}
      targetPort: {{ .Values.db.exporter.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "stockit-backend-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.db.name }}