{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stockit-backend-chart.fullname" . }}-redis-pvc
  labels:
    {{- include "stockit-backend-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.redis.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}

